FROM python:3.13

WORKDIR /site
COPY . /site

EXPOSE 8080

CMD ["python", "-m", "http.server", "8080", "--bind", "0.0.0.0"]

FROM python:3.13

WORKDIR /site
COPY . /site

EXPOSE 8080

CMD ["python", "-m", "http.server", "8080", "--bind", "0.0.0.0"]